export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/main'
export const OPERATION_ROUTE = '/operation'
export const ACCOUNT_ROUTE = '/account'